// Global UI Action
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_SUBMENU = 'OPEN_SUBMENU';
export const CLOSE_ALL_SUBMENU = 'CLOSE_ALL_SUBMENU';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_RANDOM_THEME = 'CHANGE_RANDOM_THEME';
export const CHANGE_MODE = 'CHANGE_MODE';
export const CHANGE_GRADIENT = 'CHANGE_GRADIENT';
export const CHANGE_DECO = 'CHANGE_DECO';
export const CHANGE_BG_POSITION = 'CHANGE_BG_POSITION';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const LOAD_PAGE = 'LOAD_PAGE';

// Tree Table
export const TOGGLE_TREE = 'TOGGLE_TREE';

// Redux Form
export const INIT = 'INIT';
export const CLEAR = 'CLEAR';

// Crud Table
export const FETCH_DATA = 'FETCH_DATA';
export const ADD_EMPTY_ROW = 'ADD_EMPTY_ROW';
export const UPDATE_ROW = 'UPDATE_ROW';
export const REMOVE_ROW = 'REMOVE_ROW';
export const EDIT_ROW = 'EDIT_ROW';
export const SAVE_ROW = 'SAVE_ROW';

// Crud Form Table
export const FETCH_DATA_FORM = 'FETCH_DATA_FORM';
export const ADD_NEW = 'ADD_NEW';
export const CLOSE_FORM = 'CLOSE_FORM';
export const SUBMIT_DATA = 'SUBMIT_DATA';
export const REMOVE_ROW_FORM = 'REMOVE_ROW_FORM';
export const EDIT_ROW_FORM = 'EDIT_ROW_FORM';

// Social Media
// export const FETCH_TIMELINE_DATA = 'FETCH_TIMELINE_DATA';
// export const FETCH_COMMENT_DATA = 'FETCH_COMMENT_DATA';
// export const POST = 'POST';
// export const POST_COMMENT = 'POST_COMMENT';
// export const TOGGLE_LIKE = 'TOGGLE_LIKE';

// Ecommerce
export const FETCH_PRODUCT_DATA = 'FETCH_PRODUCT_DATA';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SHOW_DETAIL_PRODUCT = 'SHOW_DETAIL_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const CHECKOUT = 'CHECKOUT';

// Contact
export const FETCH_CONTACT_DATA = 'FETCH_CONTACT_DATA';
export const SHOW_DETAIL_CONTACT = 'SHOW_DETAIL_CONTACT';
export const HIDE_DETAIL = 'HIDE_DETAIL';
export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const SUBMIT_CONTACT = 'SUBMIT_CONTACT';
export const CLOSE_CONTACT_FORM = 'CLOSE_CONTACT_FORM';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SEARCH_CONTACT = 'SEARCH_CONTACT';

// Chat
export const FETCH_CHAT_DATA = 'FETCH_CHAT_DATA';
export const SHOW_CHAT = 'SHOW_CHAT';
export const HIDE_CHAT = 'HIDE_CHAT';
export const SEND_CHAT = 'SEND_CHAT';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';

// Email
export const FETCH_EMAIL_DATA = 'FETCH_EMAIL_DATA';
export const OPEN_MAIL = 'OPEN_MAIL';
export const FILTER_MAIL = 'FILTER_MAIL';
export const COMPOSE_MAIL = 'COMPOSE_MAIL';
export const DISCARD_MESSAGE = 'DISCARD_MESSAGE';
export const SEARCH_MAIL = 'SEARCH_MAIL';
export const SEND_MAIL = 'SEND_MAIL';
export const MOVE_TO = 'MOVE_TO';
export const DELETE_MAIL = 'DELETE_MAIL';
export const TOGGLE_STARED = 'TOGGLE_STARED';

// Calendar
export const FETCH_CALENDAR_DATA = 'FETCH_CALENDAR_DATA';
export const ADD_EVENT = 'ADD_EVENT';
export const DISCARD_EVENT = 'DISCARD_EVENT';
export const SUBMIT_EVENT = 'SUBMIT_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';

// Task Board
export const FETCH_BOARD_DATA = 'FETCH_BOARD_DATA';
export const ADD_BOARD = 'ADD_BOARD';
export const DISCARD_BOARD = 'DISCARD_BOARD';
export const SUBMIT_BOARD = 'SUBMIT_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';

// Notification Form
export const CLOSE_NOTIF = 'CLOSE_NOTIF';

// Register Form
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// Login Form
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_COOKIE = 'APPAVOCAT_COOKIE';

// Directory
export const DIRECTORY_ALL_SUCCESS = 'DIRECTORY_ALL_SUCCESS';
export const GET_ALL_FOLDER_SUCCESS = 'GET_ALL_FOLDER_SUCCESS';
export const GET_ALL_FOLDER_ERROR = 'GET_ALL_FOLDER_ERROR';
export const DIRECTORY_ALL_ERROR = 'DIRECTORY_ALL_ERROR';
export const CREATE_DIRECTORY_SUCCESS = 'CREATE_DIRECTORY_SUCCESS';
export const CREATE_DIRECTORY_ERROR = 'CREATE_DIRECTORY_ERROR';
export const DELETE_DIRECTORY_SUCCESS = 'DELETE_DIRECTORY_SUCCESS';
export const DELETE_DIRECTORY_ERROR = 'DELETE_DIRECTORY_ERROR';

// Folder
export const FOLDER_ALL_SUCCESS = 'FOLDER_ALL_SUCCESS';
export const FOLDER_ALL_ERROR = 'FOLDER_ALL_ERROR';
export const GET_ALL_DOCUMENT_SUCCESS = 'GET_ALL_DOCUMENT_SUCCESS';
export const GET_ALL_DOCUMENT_ERROR = 'GET_ALL_DOCUMENT_ERROR';
export const GET_ALL_CASEWORKER_SUCCESS = 'GET_ALL_CASEWORKER_SUCCESS';
export const GET_ALL_CASEWORKER_ERROR = 'GET_ALL_CASEWORKER_ERROR';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_ERROR = 'CREATE_FOLDER_ERROR';
export const DELETE_FOLDER_SUCCESS = 'DELETE_FOLDER_SUCCESS';
export const DELETE_FOLDER_ERROR = 'DELETE_FOLDER_ERROR';

// Document
export const DOCUMENT_ALL_SUCCESS = 'DOCUMENT_ALL_SUCCESS';
export const DOCUMENT_ALL_ERROR = 'DOCUMENT_ALL_ERROR';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_ERROR = 'CREATE_DOCUMENT_ERROR';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_ERROR = 'DELETE_DOCUMENT_ERROR';

// CaseWorker
export const GET_CASEWORKER_SUCCESS = 'GET_CASEWORKER_SUCCESS';
export const GET_CASEWORKER_ERROR = 'GET_CASEWORKER_ERROR';
export const CASEWORKER_ALL_SUCCESS = 'CASEWORKER_ALL_SUCCESS';
export const CASEWORKER_ALL_ERROR = 'CASEWORKER_ALL_ERROR';
export const CREATE_CASEWORKER_SUCCESS = 'CREATE_CASEWORKER_SUCCESS';
export const CREATE_CASEWORKER_ERROR = 'CREATE_CASEWORKER_ERROR';
export const DELETE_CASEWORKER_SUCCESS = 'DELETE_CASEWORKER_SUCCESS';
export const DELETE_CASEWORKER_ERROR = 'DELETE_CASEWORKER_ERROR';
export const FETCH_CASEWORKER_DATA = 'FETCH_CASEWORKER_DATA';
export const SHOW_DETAIL_CASEWORKER = 'SHOW_DETAIL_CASEWORKER';
export const ADD_CASEWORKER = 'ADD_CASEWORKER';
export const EDIT_CASEWORKER = 'EDIT_CASEWORKER';
export const SUBMIT_CASEWORKER = 'SUBMIT_CASEWORKER';
export const CLOSE_CASEWORKER_FORM = 'CLOSE_CASEWORKER_FORM';
export const DELETE_CASEWORKER = 'DELETE_CASEWORKER';
export const SEARCH_CASEWORKER = 'SEARCH_CASEWORKER';

// Customer
export const GET_CUSTOMER_SUCCESS = 'GET_CASEWORKER_SUCCESS';
export const GET_CUSTOMER_ERROR = 'GET_CASEWORKER_ERROR';
export const CUSTOMER_ALL_SUCCESS = 'CUSTOMER_ALL_SUCCESS';
export const CUSTOMER_ALL_ERROR = 'CUSTOMER_ALL_ERROR';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR';
export const FETCH_CUSTOMER_DATA = 'FETCH_CUSTOMER_DATA';
export const SHOW_DETAIL_CUSTOMER = 'SHOW_DETAIL_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const SUBMIT_CUSTOMER = 'SUBMIT_CUSTOMER';
export const CLOSE_CUSTOMER_FORM = 'CLOSE_CUSTOMER_FORM';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER';

// TimeLine
export const TIMELINE_ALL_SUCCESS = 'TIMELINE_ALL_SUCCESS';
export const TIMELINE_ALL_ERROR = 'TIMELINE_ALL_ERROR';
export const FETCH_TIMELINE_DATA = 'FETCH_TIMELINE_DATA';
export const POST = 'POST';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';
export const FETCH_COMMENT_DATA = 'FETCH_COMMENT_DATA';
export const POST_COMMENT = 'POST_COMMENT';


//Registration multi form step
export const GO_TO_NEXT_PAGE_SUCCESS = 'GO_TO_NEXT_PAGE_SUCCESS';
export const GO_TO_NEXT_PAGE_FAILURE = 'GO_TO_NEXT_PAGE_FAILURE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const GO_TO_DEMO = 'GO_TO_DEMO';
export const GO_TO_BASIC = 'GO_TO_BASIC';
export const GO_TO_PREMIUM = 'GO_TO_PREMIUM';
